gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      gripper: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains: # Required because we're controlling an effort interface
    gripper: {p: 100,  d: 1, i: 1, i_clamp: 1}
